sudo: false

language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install: make updatedeps

script:
  - go get -u github.com/mitchellh/gox
  - GOMAXPROCS=2 make
  - GOMAXPROCS=2 make bin
  #- go test -race ./...

addons:
  artifacts: 
    debug: true
    paths:
    - $GOPATH/bin/*
  

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#packer-tool"
    skip_join: true
    use_notice: true

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
