sudo: false

language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install: make updatedeps

script:
  - go get -u github.com/mitchellh/gox
  - GOMAXPROCS=2 make
  - GOMAXPROCS=2 make bin
  - ls -R $HOME
  #- go test -race ./...

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIESE3UFGS6RVI4ZQ
  secret_access_key:
    secure: koWwSPXm8coZkX7pkKALVLco9wUBszGbwyD1tSfvY5XERKGdgPaMTpi23o06ax9rI1b1WXcDhU8gxWIzPT/sKcsAVOL5b8GViPFXLN1Lgjfz80rXkL8tAWCKT3TWsN/ud6eNMjOHypWynLrg6m/le+SedihtBp7AJaP8QdpycTECI1+xNAn+evmU4Jw/lJxQLOCVp83vbDNqNoKhsILRGqhgU6LRSyXMGl9Z5kO/BmVz3fU5WdenKIOzaxzBg4he04Acwl5lH0LZIU4y1EcIkZx/idhtwTTl7TtLCy2Gctj8AMa3qIKXwo0GqFuSYvi+411HEVZ/CS4jDit6esrXssXRBxSIpLBQFlXoKJTPUM7zWuw6cTsYbn1CT0Xz4E3dhwL6rZeLt5eeDH53AZv0tFhL5YKGdVEgVQ4OZwPdvZWn20vn7j7GCgKO41iHD7w8UtewEe0BjUWA3b/FK+Zv2y+6kZdEnQ8Nh/pQeoLuzJxV1OEKWg8pItffRPOf2n8znJwyB/apmI5nvjEuDiV+eYVJtDcuxAMU4yDF+3MXLunirF5cZURkDyJsAXaLeeuLQBbnEp0h5zgRPsmw7qU+vADjZQo7uIQVX+OUidV6WELRjs/sGy+jkToijzrU5huFJxeP7smr4sG59JW8XRIklczxbiQcswZX/WXsvZi3cCw=
  bucket: ge-packer-builds
  local-dir: "/home/travis/gopath/bin"
  upload-dir: built
  acl: public_read
  on:
    repo: aidansteele/packer


branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
