sudo: false

language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install: make updatedeps

script:
  - go get -u github.com/mitchellh/gox
  - GOMAXPROCS=2 make
  - GOMAXPROCS=2 make bin
  - ls -R $HOME
  #- go test -race ./...

addons:
  artifacts: 
    debug: true
    paths:
    - $(ls $GOPATH/bin/* | tr "\n" ":")
  

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
